'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { store } from '../app/redux/store'
import { Provider } from 'react-redux'
import Header from "./Comman/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Provider store={store} >
        <Header/>
          {children}
        </Provider>

      </body>
    </html>
  );
}
